[tool.cruft]
skip = ["pkglist.txt", "README.md", "virustotal", "tests"]

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
extend-select = ["E501", "D", "DOC"]
ignore = ["D104", "D203", "D213"]
preview = true

[tool.ruff.lint.pydocstyle]
convention = "google"
